pipeline {
    agent any

    environment {
        TARGET_BRANCH = 'front-dev'  
        JENKINS_USER = 'boricori'
        JENKINS_TOKEN = credentials('dbstjr9898')
    }

    stages {
        stage('Cleanup Workspace') {
            steps {
                deleteDir() 
            }
        }
        stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                              branches: [[name: '*/front-dev']],
                              doGenerateSubmoduleConfigurations: false,
                              extensions: [[$class: 'CleanCheckout']],
                              userRemoteConfigs: [[url: 'https://lab.ssafy.com/s11-webmobile1-sub2/S11P12B205.git',
                              credentialsId: 'dbstjr9898']]  
                    ])
                }
            }
        }
        stage('Copy .env.local') {
            steps {
                script {
                    withCredentials([file(credentialsId: 'env-local', variable: 'APP_PROPERTIES')]) {
                        sh 'cp $APP_PROPERTIES FrontEnd/.env.local'
                        sh 'cat FrontEnd/.env.local'
                    }
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t frontend -f FrontEnd/Dockerfile FrontEnd/.'
                }
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                script {
                    sh '''
                        ssh -o StrictHostKeyChecking=no -i /var/jenkins_home/.ssh/I11B205T.pem ubuntu@i11b205.p.ssafy.io '
                        cd /home/ubuntu/plog &&
                        docker-compose stop frontend && 
                        docker-compose rm -f frontend &&
                        docker-compose up -d frontend &&
                        docker image prune -f
                        '
                    '''
                }
            }
        }
    }
    post {
        success {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'good', 
                message: "빌드 성공: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)", 
                endpoint: 'https://meeting.ssafy.com/hooks/grehwxtazif4uee6c9ojhuii3y', 
                channel: 'Jenkins'
                )
            }
        }
        failure {
        	script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (color: 'danger', 
                message: "빌드 실패: ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID}(${Author_Name})\n(<${env.BUILD_URL}|Details>)", 
                endpoint: 'https://meeting.ssafy.com/hooks/grehwxtazif4uee6c9ojhuii3y', 
                channel: 'Jenkins'
                )
            }
        }
    }

}

